// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.Data;

#nullable disable

namespace Stock.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606073701_RenameUserWatchRecordToTdxCurrentKlineView")]
    partial class RenameUserWatchRecordToTdxCurrentKlineView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.Data.Entities.KlineBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TradeTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Stock.Data.Entities.StockInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("StockInfo", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.TdxCurrentKlineView", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Resolution")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Resolution");

                    b.ToTable("TdxCurrentKlineView", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.Kline15m", b =>
                {
                    b.HasBaseType("Stock.Data.Entities.KlineBase");

                    b.HasIndex("Symbol", "TradeTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Kline15m_Symbol_Time");

                    b.ToTable("Kline_15m", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.Kline1d", b =>
                {
                    b.HasBaseType("Stock.Data.Entities.KlineBase");

                    b.HasIndex("Symbol", "TradeTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Kline1d_Symbol_Time");

                    b.ToTable("Kline_1d", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.Kline1m", b =>
                {
                    b.HasBaseType("Stock.Data.Entities.KlineBase");

                    b.HasIndex("Symbol", "TradeTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Kline1m_Symbol_Time");

                    b.ToTable("Kline_1m", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.Kline1mo", b =>
                {
                    b.HasBaseType("Stock.Data.Entities.KlineBase");

                    b.HasIndex("Symbol", "TradeTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Kline1mo_Symbol_Time");

                    b.ToTable("Kline_1mo", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.Kline1w", b =>
                {
                    b.HasBaseType("Stock.Data.Entities.KlineBase");

                    b.HasIndex("Symbol", "TradeTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Kline1w_Symbol_Time");

                    b.ToTable("Kline_1w", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.Kline30m", b =>
                {
                    b.HasBaseType("Stock.Data.Entities.KlineBase");

                    b.HasIndex("Symbol", "TradeTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Kline30m_Symbol_Time");

                    b.ToTable("Kline_30m", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.Kline5m", b =>
                {
                    b.HasBaseType("Stock.Data.Entities.KlineBase");

                    b.HasIndex("Symbol", "TradeTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Kline5m_Symbol_Time");

                    b.ToTable("Kline_5m", (string)null);
                });

            modelBuilder.Entity("Stock.Data.Entities.Kline60m", b =>
                {
                    b.HasBaseType("Stock.Data.Entities.KlineBase");

                    b.HasIndex("Symbol", "TradeTime")
                        .IsUnique()
                        .HasDatabaseName("IX_Kline60m_Symbol_Time");

                    b.ToTable("Kline_60m", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
